Feature/youtube apis gsd 1890
CreatorStack/backbone pull request #11
Opened 2021-11-03 08:36 UTC by aashishAil

## Relevant Documentation Links
- https://creatorstack.atlassian.net/wiki/spaces/PF/pages/629309585/YouTube+Video+Scraping+v2.0

## Relevant Jira Links
- https://creatorstack.atlassian.net/browse/GSD-1890

## Other Relevant PRs
- 

## Changes
- Added common youtube data fetch API's
- Added generic logger 
- Added generic new-relic profiler

### Changes Include

-   [ ] Bug fix 🐛 (non-breaking change which fixes an issue)
-   [ ] New feature ✨ (non-breaking change which adds functionality)
-   [ ] Breaking change 😢 (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
-   [ ] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)
-   [ ] Performance ⚡ (code change that improves performance)

### Checklist

-   [ ] I have commented on my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Requires migrations
-   [ ] Requires dependency update
-   [ ] Breaking API Change
-   [ ] I have added proper logs for production debugging
-   [ ] I have added performance (APM) monitoring checkpoints
-   [ ] I have added unit tests

## Screenshots (if any)
(prefer animated gif)

## User Acceptance Tests

### Test #1

Description

- [ ] Acceptance Creteria #1
- [ ] Acceptance Creteria #2

2021-11-03 09:10 UTC, mrasif approved these changes

2021-11-08 12:27 UTC, MrDHat requested changes

2021-11-08 12:27 UTC, MrDHat commented on repository/youtube.go
> +type YoutubeRepo interface {
shouldn't this be in the youtube service?

2021-11-08 12:28 UTC, aashishAil commented on repository/youtube.go
> +type YoutubeRepo interface {
This is common for both Fanclub and youtube service, hence moving it here

2021-11-12 12:16 UTC, aashishAil commented on repository/youtube.go
> +type YoutubeRepo interface {
This has been removed

2021-11-12 12:28 UTC, krishnamurthypranesh commented on utils/profiler.go
> +	INTERACTION = iota
Question: Is `iota` coming from an import?

2021-11-12 12:30 UTC, krishnamurthypranesh approved these changes

2021-11-12 12:30 UTC, aashishAil commented on utils/profiler.go
> +	INTERACTION = iota
this is for new-relic specifically. Their convention

2021-11-12 12:37 UTC, merged