chore: added integration with ably
CreatorStack/backbone pull request #24
Opened 2021-12-23 13:43 UTC by aashishAil

## Relevant Documentation Links
-

## Relevant Jira Links
-
-

## Other Relevant PRs
-

## Changes

(Description of changes)

### Changes Include

-   [ ] Bug fix 🐛 (non-breaking change which fixes an issue)
-   [ ] New feature ✨ (non-breaking change which adds functionality)
-   [ ] Breaking change 😢 (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
-   [ ] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)
-   [ ] Performance ⚡ (code change that improves performance)

### Checklist

-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Requires migrations
-   [ ] Requires dependency update
-   [ ] Breaking API Change
-   [ ] I have added proper logs for production debugging
-   [ ] I have added performance (APM) monitoring checkpoints
-   [ ] I have added unit tests

## Screenshots (if any)
(prefer animated gif)

## User Acceptance Tests

### Test #1

Description

- [ ] Acceptance Creteria #1
- [ ] Acceptance Creteria #2

2021-12-23 16:09 UTC, MrDHat requested changes
Can we move it to a separate package called realtime or something instead of utils?

2021-12-24 05:02 UTC, MrDHat approved these changes

2021-12-28 07:04 UTC, rupamJoshi approved these changes

2021-12-28 14:26 UTC, krishnamurthypranesh approved these changes

2021-12-29 09:05 UTC, merged