chore: adding queue to backbone
CreatorStack/backbone pull request #28
Opened 2022-01-15 09:10 UTC by mrasif

## Relevant Documentation Links
-

## Relevant Jira Links
-
-

## Other Relevant PRs
-

## Changes

(Description of changes)

### Changes Include

-   [ ] Bug fix 🐛 (non-breaking change which fixes an issue)
-   [x] New feature ✨ (non-breaking change which adds functionality)
-   [ ] Breaking change 😢 (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
-   [ ] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)
-   [ ] Performance ⚡ (code change that improves performance)

### Checklist

-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Requires migrations
-   [ ] Requires dependency update
-   [ ] Breaking API Change
-   [ ] I have added proper logs for production debugging
-   [ ] I have added performance (APM) monitoring checkpoints
-   [ ] I have added unit tests

## Screenshots (if any)
(prefer animated gif)

## User Acceptance Tests

### Test #1

Description

- [ ] Acceptance Creteria #1
- [ ] Acceptance Creteria #2

2022-01-15 09:26 UTC, MrDHat requested changes

2022-01-15 09:26 UTC, MrDHat commented on utils/event.go
> +package utils
Let's move this to queue package itself

2022-01-15 09:26 UTC, MrDHat commented on queue/queue.go
> +		nstsClientName:  nstsClientName,
nats

2022-01-17 11:52 UTC, krishnamurthypranesh approved these changes

2022-01-20 09:56 UTC, MrDHat approved these changes

2022-01-25 09:23 UTC, aashishAil commented on utils/common.go
> +		unit = "hour"
we should transfer it to package ```utils/time``` so that it is easily mockable

2022-01-25 09:24 UTC, aashishAil approved these changes

2022-01-27 10:43 UTC, krishnamurthypranesh commented on utils/common.go
> +		unit = "hour"
Done

2022-01-27 10:46 UTC, merged